### ISSUE TITLE
Unable to resolve symbol: join in this context 

### ISSUE THREAD

**Issue by adeel** [Raynes/lein-bin#20]
For some reason I started getting the following error:

 $ lein bin
Exception in thread "main" java.lang.Exception: Unable to resolve symbol: join in this context (bin.clj:13)
    at clojure.lang.Compiler.analyze(Compiler.java:5206)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3037)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5372)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:4671)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:4942)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5370)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5358)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:4671)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:4942)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5370)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5358)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:4671)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:4329)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3174)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5368)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5358)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:799)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5370)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5358)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.access$100(Compiler.java:36)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:439)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5370)
    at clojure.lang.Compiler.analyze(Compiler.java:5191)
    at clojure.lang.Compiler.analyze(Compiler.java:5152)
    at clojure.lang.Compiler.eval(Compiler.java:5429)
    at clojure.lang.Compiler.load(Compiler.java:5858)
    at clojure.lang.RT.loadResourceScript(RT.java:340)
    at clojure.lang.RT.loadResourceScript(RT.java:331)
    at clojure.lang.RT.load(RT.java:409)
    at clojure.lang.RT.load(RT.java:381)
    at clojure.core$load$fn__4519.invoke(core.clj:4915)
    at clojure.core$load.doInvoke(core.clj:4914)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:4729)
    at clojure.core$load_lib.doInvoke(core.clj:4766)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$load_libs.doInvoke(core.clj:4800)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$require.doInvoke(core.clj:4881)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at leiningen.core$resolve_task.invoke(core.clj:208)
    at leiningen.core$apply_task.invoke(core.clj:258)
    at leiningen.core$_main.doInvoke(core.clj:329)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$_main.invoke(core.clj:332)
    at user$eval73.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5425)
    at clojure.lang.Compiler.eval(Compiler.java:5392)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:377)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Unable to resolve symbol: join in this context
    at clojure.lang.Compiler.resolveIn(Compiler.java:5678)
    at clojure.lang.Compiler.resolve(Compiler.java:5622)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:5585)
    at clojure.lang.Compiler.analyze(Compiler.java:5173)
    ... 76 more

**Comment by adeel** [comment]
Sorry, this computer was apparently running Leiningen 1.
